name: study_ferry_pokemon
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  change_app_package_name: ^1.3.0
  ferry: ^0.16.0+1
  ferry_flutter: ^0.9.0-dev.6
  ferry_hive_store: ^0.5.2
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  gql_build: ^0.11.0+1
  gql_http_link: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.4
  ferry_generator: ^0.10.0

flutter:
  uses-material-design: true
